### ISSUE TITLE
서버사이드 소개의 내용 중 ...

### ISSUE THREAD

**Issue by syseo78** [YoonJoon/KGardenDevProcessStandard#3]
**Is your feature request related to a problem? Please describe.**
[서버사이드 소개](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/introServer.md)

"서버사이드 프로그래밍을 사용하면 대신 정보를 데이터베이스에 저장하고~"의 내용중 
"...대신 정보를..."의 표현이 모호한것 같습니다..

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YoonJoon** [comment]
"서버사이드 프로그래밍을 사용하면 대신 정보를 데이터베이스에 저장하고 ~"를 "서버사이드 프로그래밍을 사용하면 정보를 데이터베이스에 대신 저장하고 ~"로 고쳤습니다. 감사합니다.
