### ISSUE TITLE
서버사이드 웹 프레임워크의 본문 중 동일 문단이 두번 타이핑되었습니다. 

### ISSUE THREAD

**Issue by syseo78** [YoonJoon/KGardenDevProcessStandard#5]
**Is your feature request related to a problem? Please describe.**
[서버사이드 웹 프레임워크](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/webFramework.md)

Django 모델은 데이터베이스 검색을위한 간단한 쿼리 API를 제공합니다. 이것은 서로 다른 조건(예 : 일치, 대소 문자를 구별, 크다 등)을 사용하여 한 번에 여러 필드와 비교할 수 있으며 복잡한 명령문을 지원할 수 있습니다 (예 : 팀이름이 "Fr"로 시작하거나 "al"로 끝나는 U11 팀에서 검색할 수 있습니다).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YoonJoon** [comment]
수정하였습니다. 감사합니다.
