### ISSUE TITLE
오타, 띄어쓰기 등

### ISSUE THREAD

**Issue by syseo78** [YoonJoon/KGardenDevProcessStandard#6]
**Is your feature request related to a problem? Please describe.**
[웹서버란](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/whatIsWebserver.md)
"다른 패이지에서" -> 오타 "페이지"

[클라이언트-서버 개요](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/clientServerOverview.md)
"이떄" ->오타 "이때"

[서버사이드 웹 프레임워크](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/webFramework.md)
"검색을위한" -> 띄어쓰기 "검색을 위한" 
 "때떄로" ->오타 "때때로"
"애플리케이션을위한" -> 띄어쓰기 "애플리케이션을 위한"
"사용하는 것을 따른는 것이 타당합니다." -> 오타 "따르는"
"문서화가 잘 되을 가능성이 크므로" -> 오타 "되었을" 또는 "됐을"
"지에따라" -> 띄어쓰기 "지에 따라"
"라스베리 파이" -> 오타 "라즈베리 파이"
"Node.js를위한" -> 띄어쓰기 "Node.js를 위한"
"실행하기위한 브라우저없는 환경입니다" -> 띄어쓰기 "실행하기 위한 브라우저 없는 환경입니다"
"기반으로하므로" -> 띄어쓰기 "기반으로 하므로" 
"프레임 워크" -> 띄어쓰기 통일 "프레임워크"
"최첨단 기술을 사용하여**이** 이 아이디어를" -> 오타 "최첨단 기술을 사용하여 이 아이디어를"
"서버사이드 코드를보다" -> 띄어쓰기 "서버사이드 코드를 보다"
"선택하기위한" -> 띄어쓰기 "선택하기 위한"

[웹사이트 보안](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/webSiteSecurity.md)
"활성화할 수 있다는 것입니다 ." -> 마침표 띄어쓰기 "활성화할 수 있다는 것입니다."
"읽으면서 웹 응용프로그램이 브라우저가 보내는 데이터를 충분히 신뢰할 때 위협이 가장 성공적이었는지 보여줍니다." -> 데이터를 신뢰할때 가장 위협적이라는것인지요? 어떤 의미인지 이해가 잘 안가요~ 
"공격자가 쿠키를 갖으면 " -> 오타 "공격자가 쿠키를 가지면"

**Comment by YoonJoon** [comment]
다 반영하였습니다. 고맙습니다.
