### ISSUE TITLE
용어 변경?

### ISSUE THREAD

**Issue by syseo78** [YoonJoon/KGardenDevProcessStandard#7]
**Is your feature request related to a problem? Please describe.**
[웹사이트 보안](https://github.com/YoonJoon/KGarden/blob/master/AboutServersideWebProgramming/FirstStep/webSiteSecurity.md)
"해결책은 사용하기 전에 이를 소독하는 것입니다."

**Describe the solution you'd like**
소독이란 표현이 애매한것 같아요

**Describe alternatives you've considered**

**Additional context**

**Comment by YoonJoon** [comment]
"소독"을 "검사"로 변경하였습니다. 감사합니다.
